#!/usr/bin/env bash
# This script is used to generate Judge0 config file for FU-OJ

# Apply fuoj.conf to judge0.conf
# Ignore keys that are not exist in judge0.conf
# Overwrite the default value

SOURCE=/etc/fuoj/default/judge0.conf
CHANGES=(
    /etc/fuoj/fuoj.conf
)
DESTINATION=/etc/fuoj/judge0.conf

declare -A judge0_conf
declare -A merge_changes

if [ -f "$SOURCE" ]; then
    while IFS='=' read -r key value; do
        if [[ ! "$key" =~ ^# && -n "$key" ]]; then
            judge0_conf["$key"]="$value"
            merge_changes["$key"]="$value"
        fi
    done <"$SOURCE"
fi

for file in "${CHANGES[@]}"; do
    if [ -f "$file" ]; then
        while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
                merge_changes["$key"]="$value"
            fi
        done <"$file"
    fi
done

# Apply changes to judge0.conf
for key in "${!judge0_conf[@]}"; do
    if [ -n "${merge_changes[$key]}" ]; then
        judge0_conf["$key"]="${merge_changes[$key]}"
    fi
done

# Write to judge0.conf
tee "$DESTINATION" >/dev/null <<EOF
# FU-OJ Judge0 Configuration
# This file is generated by FU-OJ setup script

$(for key in "${!judge0_conf[@]}"; do echo "$key=${judge0_conf[$key]}"; done)
EOF
