name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install OpenSSH Client
        run: sudo apt-get install -y openssh-client
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/fuoj/FU-OJ
            git stash
            git pull
          EOF
