name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare OpenSSH Client
        shell: bash
        run: |
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          echo "$SSH_HOST" > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private_key $SSH_USER@$SSH_HOST <<EOF
            SOURCE_DIR="/usr/src/fuoj"

            cd "$SOURCE_DIR" || exit 1

            SCRIPT_DIR="$SOURCE_DIR/scripts"

            for script in "$SCRIPT_DIR/03.build.d"/*; do
              bash "$script"
            done
          EOF
